-- MySQL Script generated by MySQL Workbench
-- Tue Dec 15 14:53:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mamografia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mamografia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mamografia` DEFAULT CHARACTER SET utf8 ;
USE `mamografia` ;

-- -----------------------------------------------------
-- Table `mamografia`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamografia`.`paciente` (
  `idpaciente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpaciente`, `cpf`),
  UNIQUE INDEX `cpfpaciente_UNIQUE` (`idpaciente` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mamografia`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamografia`.`exame` (
  `idexame` VARCHAR(10) NOT NULL,
  `caracteristicatecido` VARCHAR(1) NOT NULL,
  `classeanormalidade` VARCHAR(6) NOT NULL,
  `gravidadeanormalidade` VARCHAR(1) NULL,
  `x` INT UNSIGNED NULL,
  `y` INT UNSIGNED NULL,
  `raio` INT UNSIGNED NULL,
  PRIMARY KEY (`idexame`),
  UNIQUE INDEX `idexame_UNIQUE` (`idexame` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mamografia`.`possui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mamografia`.`possui` (
  `idexame` VARCHAR(10) NOT NULL,
  `idpaciente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idexame`, `idpaciente`),
  UNIQUE INDEX `idexame_UNIQUE` (`idexame` ASC) VISIBLE,
  INDEX `fk_possui_paciente1_idx` (`idpaciente` ASC) VISIBLE,
  CONSTRAINT `fk_possui_exame`
    FOREIGN KEY (`idexame`)
    REFERENCES `mamografia`.`exame` (`idexame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_possui_paciente1`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `mamografia`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
