/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ExameDAO;
import dao.PacienteDAO;
import dto.Exame;
import dto.Paciente;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author heloh
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public TelaCadastro() {
        initComponents();
    }

    TelaCadastro(TelaLogin aThis) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCaracteristicaDoTecido = new javax.swing.JLabel();
        lblClasseDaNormalidade = new javax.swing.JLabel();
        lblGravidadeDaFormalidade = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        lblRaio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtX = new javax.swing.JTextField();
        txtY = new javax.swing.JTextField();
        txtRaio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        btnAdicionarImagem = new javax.swing.JButton();
        txtNomeCaminho = new javax.swing.JTextField();
        rbtnCarF = new javax.swing.JRadioButton();
        rbtnCarG = new javax.swing.JRadioButton();
        rbtnCarD = new javax.swing.JRadioButton();
        rbtnGravB = new javax.swing.JRadioButton();
        rbtnGravM = new javax.swing.JRadioButton();
        rbtnClassCalc = new javax.swing.JRadioButton();
        rbtnClassCirc = new javax.swing.JRadioButton();
        rbtnClassSpic = new javax.swing.JRadioButton();
        rbtnClassMisc = new javax.swing.JRadioButton();
        rbtnClassArch = new javax.swing.JRadioButton();
        rbtnClassAsym = new javax.swing.JRadioButton();
        rbtnClassNorm = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro");

        lblNome.setText("Nome do paciente:");

        lblCPF.setText("CPF:");

        jLabel5.setText("Dados do paciente:");

        lblCaracteristicaDoTecido.setText("Caracteristica do tecido: ");

        lblClasseDaNormalidade.setText("Classe da normalidade:");

        lblGravidadeDaFormalidade.setText("Gravidade da formalidade:");

        lblX.setText("X:");

        lblY.setText("Y:");

        lblRaio.setText("Raio:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Adicionar um exame:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Upload:");

        btnAdicionarImagem.setText("Add");
        btnAdicionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarImagemActionPerformed(evt);
            }
        });

        txtNomeCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCaminhoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnCarF);
        rbtnCarF.setText("F - Fatty");

        buttonGroup1.add(rbtnCarG);
        rbtnCarG.setText("G - Fatty-glandular");

        buttonGroup1.add(rbtnCarD);
        rbtnCarD.setText("D - Dense-glandular");
        rbtnCarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCarDActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbtnGravB);
        rbtnGravB.setText("B - Benign");

        buttonGroup3.add(rbtnGravM);
        rbtnGravM.setText(" M - Malignant");

        buttonGroup2.add(rbtnClassCalc);
        rbtnClassCalc.setText("CALC ");

        buttonGroup2.add(rbtnClassCirc);
        rbtnClassCirc.setText("CIRC");

        buttonGroup2.add(rbtnClassSpic);
        rbtnClassSpic.setText("SPIC");
        rbtnClassSpic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnClassSpicActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtnClassMisc);
        rbtnClassMisc.setText("MISC");

        buttonGroup2.add(rbtnClassArch);
        rbtnClassArch.setText("ARCH");

        buttonGroup2.add(rbtnClassAsym);
        rbtnClassAsym.setText("ASYM");
        rbtnClassAsym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnClassAsymActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtnClassNorm);
        rbtnClassNorm.setText("NORM");

        jLabel3.setText("Coodenadas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblCPF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(txtCPF))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastrar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnAdicionarImagem)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomeCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCaracteristicaDoTecido)
                            .addComponent(rbtnCarG)
                            .addComponent(rbtnCarF)
                            .addComponent(rbtnCarD))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnClassNorm)
                            .addComponent(rbtnClassArch)
                            .addComponent(rbtnClassAsym)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnClassMisc)
                                    .addComponent(rbtnClassSpic)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblClasseDaNormalidade)
                                            .addComponent(rbtnClassCalc)
                                            .addComponent(rbtnClassCirc))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtnGravM)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblGravidadeDaFormalidade)
                                                .addComponent(rbtnGravB)))))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblX)
                                            .addComponent(lblY)
                                            .addComponent(lblRaio))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(lblCPF))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblClasseDaNormalidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnClassCalc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnClassCirc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnClassSpic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnClassMisc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnClassArch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnClassAsym)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnClassNorm))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCaracteristicaDoTecido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnCarF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnCarG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnCarD))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGravidadeDaFormalidade)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtnGravB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnGravM))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(txtRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblX)
                                            .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblY)
                                            .addComponent(txtY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRaio)))))
                        .addGap(65, 65, 65)
                        .addComponent(btnCadastrar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAdicionarImagem)
                                .addComponent(txtNomeCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addGap(38, 38, 38))))
        );

        setSize(new java.awt.Dimension(1143, 635));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Cadastrar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtNomeCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCaminhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCaminhoActionPerformed

    private void btnAdicionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarImagemActionPerformed
        // TODO add your handling code here:

        JFileChooser arquivo = new JFileChooser();
        arquivo.setDialogTitle("Selecione uma imagem");
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int opc = arquivo.showOpenDialog(this);

        if (opc == JFileChooser.APPROVE_OPTION) {

            File file = new File("Caminho");

            file = arquivo.getSelectedFile();

            try {
                /*imagem = file.getAbsolutePath();
                imagem = ImageIO.read(new File(caminhoImg));

                 */
                imagem = ImageIO.read(file);

                fileName = file.getAbsolutePath();

                txtNomeCaminho.setText(fileName);

                ImageIcon imagem = new ImageIcon(arquivo.getSelectedFile().getPath());

                //Para mostrar a imagem
                lblImagem.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(lblImagem.getWidth(), lblImagem.getHeight(), Image.SCALE_DEFAULT)));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "TelaCadastro | ADD " + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo.");
        }
    }//GEN-LAST:event_btnAdicionarImagemActionPerformed

    private void rbtnCarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCarDActionPerformed

    private void rbtnClassSpicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnClassSpicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnClassSpicActionPerformed

    private void rbtnClassAsymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnClassAsymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnClassAsymActionPerformed

    String fileName;
    BufferedImage imagem;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defalblCaracteristicaDoTecidoe="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarImagem;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCaracteristicaDoTecido;
    private javax.swing.JLabel lblClasseDaNormalidade;
    private javax.swing.JLabel lblGravidadeDaFormalidade;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRaio;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JRadioButton rbtnCarD;
    private javax.swing.JRadioButton rbtnCarF;
    private javax.swing.JRadioButton rbtnCarG;
    private javax.swing.JRadioButton rbtnClassArch;
    private javax.swing.JRadioButton rbtnClassAsym;
    private javax.swing.JRadioButton rbtnClassCalc;
    private javax.swing.JRadioButton rbtnClassCirc;
    private javax.swing.JRadioButton rbtnClassMisc;
    private javax.swing.JRadioButton rbtnClassNorm;
    private javax.swing.JRadioButton rbtnClassSpic;
    private javax.swing.JRadioButton rbtnGravB;
    private javax.swing.JRadioButton rbtnGravM;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeCaminho;
    private javax.swing.JTextField txtRaio;
    private javax.swing.JTextField txtX;
    private javax.swing.JTextField txtY;
    // End of variables declaration//GEN-END:variables

    private void Cadastrar() {
        try {
            String nome, cpf, caracteristicatecido, classeanormalidade, gravidadeanormalidade, stringX, stringY, stringRaio;
            Integer x, y, raio;
            boolean open;

            
            //pegando os dados do paciente
            nome = (txtNome.getText()).toUpperCase();
            cpf = txtCPF.getText();

            Paciente paciente = new Paciente();

            paciente.setNome(nome);
            paciente.setCpf(cpf);

          
            //pegando os dados do exame 
            if (rbtnCarF.isSelected()) {
                caracteristicatecido = "F";
            } else if (rbtnCarG.isSelected()) {
                caracteristicatecido = "G";
            } else {
                caracteristicatecido = "D";
            }

            if (rbtnClassCalc.isSelected()) {
                classeanormalidade = "CALC";
            } else if (rbtnClassCirc.isSelected()) {
                classeanormalidade = "CIRC";
            } else if (rbtnClassSpic.isSelected()) {
                classeanormalidade = "SPIC";
            } else if (rbtnClassMisc.isSelected()) {
                classeanormalidade = "MISC";
            } else if (rbtnClassArch.isSelected()) {
                classeanormalidade = "ARCH";
            } else if (rbtnClassAsym.isSelected()) {
                classeanormalidade = "ASYM";
            } else {
                classeanormalidade = "NORM";
            }

            
            if (rbtnGravB.isSelected()) {
                gravidadeanormalidade = "B";
                open = true;//?
            } else if (rbtnGravM.isSelected()) {
                gravidadeanormalidade = "M";
                open = true;//?
            } else {
                gravidadeanormalidade = "";
                open = false;//?
                
            }

            stringX = txtX.getText();
            stringY = txtY.getText();
            stringRaio = txtRaio.getText();

            if (stringX.isEmpty()) {
                x = null;
            } else {
                x = Integer.parseInt(stringX);
            }

            if (stringY.isEmpty()) {
                y = null;
            } else {
                y = Integer.parseInt(stringY);
            }

            if (stringRaio.isEmpty()) {
                raio = null;
            } else {
                raio = Integer.parseInt(stringRaio);
            }

            Exame exame = new Exame();

            exame.setCaracteristicatecido(caracteristicatecido);
            exame.setClasseanormalidade(classeanormalidade);
            exame.setGravidadeanormalidade(gravidadeanormalidade);
            exame.setX(x);
            exame.setY(y);
            exame.setRaio(raio);

            //importando tudo para o PacienteDAO
            PacienteDAO pacientedao = new PacienteDAO();
            pacientedao.cadastrarPaciente(paciente, exame);

            //pegando somente o nome da imagem
            int tam = fileName.lastIndexOf("\\");
            fileName = fileName.substring(tam + 1);

            //salvando na pasta imagens
            ImageIO.write(imagem, "jpg", new File("..\\imagens\\" + fileName));
            JOptionPane.showMessageDialog(rootPane, "Imagem enviada com sucesso");

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "TelaCadastro | cadastrar " + e);
        }
    }

}
